apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: blog-frontend
  name: blog-frontend
  namespace: blackwhale-devops
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: blog-frontend
    weight: 100
